title: Pavithra Vijayakumar
#logo: https://github.com/Pavithra-Vijayakumar/data_portfolio/commit/c89119e169373f3a301b71e705e4919a7b947f07
#description: Data Enthusiast 
show_downloads: true
theme: jekyll-theme-animal
